-- LandNote Supabase 초기 스키마 (Dexie 테이블 구조 기반)
-- Supabase Dashboard → SQL Editor에서 실행하거나 supabase db push 사용

-- profiles: auth.users 확장
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  agency_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id);
create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = id);

-- 매물
create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  status text,
  main text,
  sub text,
  trade text,
  fav boolean default false,
  fav_at timestamptz,
  data jsonb not null default '{}',
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists properties_user_id_idx on public.properties(user_id);
create index if not exists properties_deleted_at_idx on public.properties(deleted_at);

alter table public.properties enable row level security;
create policy "properties_own" on public.properties
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 고객
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  type text,
  status text,
  name text,
  phone text,
  fav boolean default false,
  data jsonb not null default '{}',
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customers_user_id_idx on public.customers(user_id);

alter table public.customers enable row level security;
create policy "customers_own" on public.customers
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 통화
create table if not exists public.call_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  pid bigint,
  cid bigint,
  date text,
  data jsonb not null default '{}',
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.call_logs enable row level security;
create policy "call_logs_own" on public.call_logs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 일정
create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  date text,
  pri text,
  pid bigint,
  data jsonb not null default '{}',
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.schedules enable row level security;
create policy "schedules_own" on public.schedules
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 임대
create table if not exists public.rentals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint,
  pid bigint,
  data jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.rentals enable row level security;
create policy "rentals_own" on public.rentals
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 폴더 (localStorage 대체)
create table if not exists public.folders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  color text,
  sort_order int default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.property_folders (
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id bigint not null references public.properties(id) on delete cascade,
  folder_id bigint not null references public.folders(id) on delete cascade,
  primary key (property_id, folder_id)
);

alter table public.folders enable row level security;
alter table public.property_folders enable row level security;

create policy "folders_own" on public.folders
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "property_folders_own" on public.property_folders
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 신규 가입 시 profiles 자동 생성
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Storage bucket: property-photos (Dashboard에서 public=false, RLS 정책 추가 필요)
-- insert into storage.buckets (id, name, public) values ('property-photos', 'property-photos', false);
